In [1]:
# 파이썬 코드 이용하여 연관규칙분석
# 신뢰도, 지지도, 향상도 고려하여 본인이 판단하기에 추천하 만한 묶음컨텐츠 제시

In [3]:
# Machine Learning Extended 패키지 설치
!pip install mlxtend

Requirement already satisfied: mlxtend in c:\users\dbwls\anaconda3\lib\site-packages (0.23.3)
Requirement already satisfied: scipy>=1.2.1 in c:\users\dbwls\anaconda3\lib\site-packages (from mlxtend) (1.13.1)
Requirement already satisfied: numpy>=1.16.2 in c:\users\dbwls\anaconda3\lib\site-packages (from mlxtend) (1.26.4)
Requirement already satisfied: pandas>=0.24.2 in c:\users\dbwls\anaconda3\lib\site-packages (from mlxtend) (2.2.2)
Requirement already satisfied: scikit-learn>=1.3.1 in c:\users\dbwls\anaconda3\lib\site-packages (from mlxtend) (1.4.2)
Requirement already satisfied: matplotlib>=3.0.0 in c:\users\dbwls\anaconda3\lib\site-packages (from mlxtend) (3.8.4)
Requirement already satisfied: joblib>=0.13.2 in c:\users\dbwls\anaconda3\lib\site-packages (from mlxtend) (1.4.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\dbwls\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\dbwls\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\dbwls\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\dbwls\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\dbwls\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (23.2)
Requirement already satisfied: pillow>=8 in c:\users\dbwls\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (10.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\dbwls\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\dbwls\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\dbwls\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\dbwls\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2023.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\dbwls\anaconda3\lib\site-packages (from scikit-learn>=1.3.1->mlxtend) (3.1.0)
Requirement already satisfied: six>=1.5 in c:\users\dbwls\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.16.0)

In [4]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

In [8]:
# 리스트의 리스트 형태로 트랜잭션 구성
dataset = [['겨울왕국', '미녀와 야수', '쥬라기 월드', '아바타', '타이타닉'],
           ['스타워즈', '어벤져스', '아이언맨'],
           ['분노의 질주', '어벤져스'],
           ['스타워즈', '아바타', '라이온 킹', '어벤져스'],
           ['쥬라기 월드', '아바타', '해리포터'],
           ['스타워즈', '겨울왕국', '미녀와 야수', '라이온 킹', '타이타닉'],
           ['스타워즈', '어벤져스', '분노의 질주', '쥬라기 월드']]

In [10]:
# TransactionEncoder는 리스트의 리스트로 구성된 트랜잭션 데이터를 NumPy 배열로 인코딩하기 위함

te = TransactionEncoder()
te_ary = te.fit(dataset).transform(dataset)
te_ary

array([[ True, False,  True, False, False,  True, False, False,  True,
         True, False],
       [False, False, False, False,  True, False,  True,  True, False,
        False, False],
       [False, False, False,  True, False, False, False,  True, False,
        False, False],
       [False,  True, False, False,  True,  True, False,  True, False,
        False, False],
       [False, False, False, False, False,  True, False, False,  True,
        False,  True],
       [ True,  True,  True, False,  True, False, False, False, False,
         True, False],
       [False, False, False,  True,  True, False, False,  True,  True,
        False, False]])

In [12]:
te.columns_

['겨울왕국',
 '라이온 킹',
 '미녀와 야수',
 '분노의 질주',
 '스타워즈',
 '아바타',
 '아이언맨',
 '어벤져스',
 '쥬라기 월드',
 '타이타닉',
 '해리포터']

In [14]:
df = pd.DataFrame(te_ary, columns=te.columns_)
df

,겨울왕국,라이온 킹,미녀와 야수,분노의 질주,스타워즈,아바타,아이언맨,어벤져스,쥬라기 월드,타이타닉,해리포터
0,True,False,True,False,False,True,False,False,True,True,False
1,False,False,False,False,True,False,True,True,False,False,False
2,False,False,False,True,False,False,False,True,False,False,False
3,False,True,False,False,True,True,False,True,False,False,False
4,False,False,False,False,False,True,False,False,True,False,True
5,True,True,True,False,True,False,False,False,False,True,False
6,False,False,False,True,True,False,False,True,True,False,False

In [20]:
# 지지도 확인
frequent_itemsets = apriori(df, min_support = 0.3, use_colnames = True)
frequent_itemsets

    support      itemsets
0  0.571429        (스타워즈)
1  0.428571         (아바타)
2  0.571429        (어벤져스)
3  0.428571      (쥬라기 월드)
4  0.428571  (어벤져스, 스타워즈)

In [22]:
# 신뢰도 확인
association_rules(frequent_itemsets, metric="confidence", min_threshold=0.3, num_itemsets = 0)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(어벤져스),(스타워즈),0.571429,0.571429,0.428571,0.75,1.3125,1.0,0.102041,1.714286,0.555556,0.6,0.416667,0.75
1,(스타워즈),(어벤져스),0.571429,0.571429,0.428571,0.75,1.3125,1.0,0.102041,1.714286,0.555556,0.6,0.416667,0.75

In [24]:
# 향상도 확인
association_rules(frequent_itemsets, metric="lift", min_threshold=1, num_itemsets = 0)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(어벤져스),(스타워즈),0.571429,0.571429,0.428571,0.75,1.3125,1.0,0.102041,1.714286,0.555556,0.6,0.416667,0.75
1,(스타워즈),(어벤져스),0.571429,0.571429,0.428571,0.75,1.3125,1.0,0.102041,1.714286,0.555556,0.6,0.416667,0.75

In [26]:
df_assoc = association_rules(frequent_itemsets, metric="lift", min_threshold=1.2, num_itemsets = 0
                        )
df_assoc.sort_values('lift', ascending=False) #lift 기준 내림차순 정렬

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(어벤져스),(스타워즈),0.571429,0.571429,0.428571,0.75,1.3125,1.0,0.102041,1.714286,0.555556,0.6,0.416667,0.75
1,(스타워즈),(어벤져스),0.571429,0.571429,0.428571,0.75,1.3125,1.0,0.102041,1.714286,0.555556,0.6,0.416667,0.75